# Site settings
title: Emily Chadwick   
email: emilyann.chadwick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I am a budding software developer living in Seattle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: 
github_username:  emilychadwick

# Build settings
markdown: kramdown
